/**
 * CarpeOS one-stop local installer core.
 * Pure helpers + injectable side effects for tests and install-local.mjs.
 */
import { spawnSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir, hostname } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

export const DEFAULT_TRUST_ZONE = "tz_local_default";
export const CONFIG_NAME = "config.json";
export const MCP_ENV_NAME = "mcp.env";
export const STATE_NAME = "install-state.json";

/**
 * @param {string} [fromUrl]
 */
export function defaultRepoRoot(fromUrl = import.meta.url) {
  // scripts/lib -> scripts -> repo root
  return resolve(dirname(fileURLToPath(fromUrl)), "../..");
}

/**
 * @param {NodeJS.ProcessEnv} [env]
 */
export function defaultHome(env = process.env) {
  return env.CARPEOS_HOME?.trim() || join(env.HOME || homedir(), ".carpeos");
}

/**
 * @param {NodeJS.ProcessEnv} [env]
 */
export function defaultBinDir(env = process.env) {
  if (env.CARPEOS_BIN_DIR?.trim()) {
    return env.CARPEOS_BIN_DIR.trim();
  }
  return join(env.HOME || homedir(), ".local", "bin");
}

/**
 * @param {string} repoRoot
 * @param {string} home
 * @param {string} trustZoneId
 * @param {string} workspaceRoot
 * @param {string} nodePath
 * @param {string} binDir
 */
export function resolveInstallEntries(repoRoot) {
  const monorepoCli = join(repoRoot, "apps/carpeos-cli/dist/index.js");
  const monorepoMcp = join(repoRoot, "apps/carpeos-mcp-server/dist/index.js");
  const npmCli = join(repoRoot, "dist/cli.js");
  const npmMcp = join(repoRoot, "dist/mcp-server.js");
  if (existsSync(npmCli) && existsSync(npmMcp)) {
    return { cli_entry: npmCli, mcp_entry: npmMcp, distribution: "npm" };
  }
  return { cli_entry: monorepoCli, mcp_entry: monorepoMcp, distribution: "git" };
}

export function buildConfig(input) {
  const entries =
    input.cliEntry && input.mcpEntry
      ? {
          cli_entry: input.cliEntry,
          mcp_entry: input.mcpEntry,
          distribution: input.distribution ?? "custom",
        }
      : resolveInstallEntries(input.repoRoot);
  return {
    schema_version: "v1",
    record_type: "carpeos_install_config",
    install_root: input.repoRoot,
    home: input.home,
    bin_dir: input.binDir,
    trust_zone_id: input.trustZoneId,
    workspace_root: input.workspaceRoot,
    node_path: input.nodePath,
    store_path: join(input.home, "carpeos.sqlite"),
    cli_entry: entries.cli_entry,
    mcp_entry: entries.mcp_entry,
    distribution: entries.distribution,
    updated_at: input.updatedAt ?? new Date().toISOString(),
  };
}

/**
 * @param {ReturnType<typeof buildConfig>} config
 */
export function renderMcpEnv(config) {
  const lines = [
    "# Generated by CarpeOS install-local. Do not commit.",
    `export CARPEOS_HOME=${shellQuote(config.home)}`,
    `export CARPEOS_MCP_STORE_PATH=${shellQuote(config.store_path)}`,
    `export CARPEOS_MCP_RUNTIME_DIR=${shellQuote(config.home)}`,
    `export CARPEOS_MCP_WORKSPACE_ROOT=${shellQuote(config.workspace_root)}`,
    `export CARPEOS_MCP_TRUST_ZONE=${shellQuote(config.trust_zone_id)}`,
    `export CARPEOS_MCP_VISIBLE_TRUST_ZONES=${shellQuote(config.trust_zone_id)}`,
    "",
  ];
  return lines.join("\n");
}

/**
 * @param {ReturnType<typeof buildConfig>} config
 * @param {"cli"|"mcp"} kind
 */
export function renderWrapper(config, kind) {
  const entry = kind === "cli" ? config.cli_entry : config.mcp_entry;
  const sourceEnv =
    kind === "mcp"
      ? `if [ -f "${escapeForDoubleQuotes(join(config.home, MCP_ENV_NAME))}" ]; then
  # shellcheck disable=SC1091
  . "${escapeForDoubleQuotes(join(config.home, MCP_ENV_NAME))}"
fi
`
      : "";
  return `#!/usr/bin/env bash
set -euo pipefail
${sourceEnv}exec ${shellQuote(config.node_path)} ${shellQuote(entry)} "$@"
`;
}

/**
 * Stable trust zone from hostname for multi-machine uniqueness (still local_device).
 * @param {string} [host]
 */
export function trustZoneFromHostname(host = hostname()) {
  const slug = host
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 24);
  const digest = createHash("sha256").update(host).digest("hex").slice(0, 8);
  const base = slug.length >= 2 ? slug : "host";
  return `tz_${base}_${digest}`.slice(0, 64);
}

/**
 * @param {string} value
 */
export function isTrustZoneId(value) {
  return /^tz_[a-z0-9][a-z0-9_-]{2,63}$/.test(value);
}

/**
 * @param {string} value
 */
export function shellQuote(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

/**
 * @param {string} value
 */
function escapeForDoubleQuotes(value) {
  return String(value).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

/**
 * @param {string} command
 */
export function commandExists(command, run = defaultRun) {
  const result = run("sh", ["-c", `command -v ${shellQuote(command)} >/dev/null 2>&1`]);
  return result.status === 0;
}

/**
 * @param {string} cmd
 * @param {string[]} args
 * @param {{ cwd?: string, env?: NodeJS.ProcessEnv }} [opts]
 */
export function defaultRun(cmd, args, opts = {}) {
  const result = spawnSync(cmd, args, {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
    cwd: opts.cwd,
    env: opts.env ?? process.env,
  });
  return {
    status: result.status ?? 1,
    stdout: result.stdout ?? "",
    stderr: result.stderr ?? "",
    error: result.error,
  };
}

/**
 * @param {{
 *   repoRoot: string,
 *   home: string,
 *   binDir: string,
 *   workspaceRoot: string,
 *   trustZoneId: string,
 *   nodePath: string,
 *   skipBuild?: boolean,
 *   skipMcp?: boolean,
 *   hosts?: string[],
 *   dryRun?: boolean,
 *   run?: typeof defaultRun,
 *   writeFile?: typeof writeFileSync,
 *   mkdir?: typeof mkdirSync,
 *   chmod?: typeof chmodSync,
 *   exists?: typeof existsSync,
 *   now?: () => Date,
 *   log?: (msg: string) => void,
 * }} options
 */
export function installLocal(options) {
  const run = options.run ?? defaultRun;
  const writeFile = options.writeFile ?? writeFileSync;
  const mkdir = options.mkdir ?? mkdirSync;
  const chmod = options.chmod ?? chmodSync;
  const exists = options.exists ?? existsSync;
  const log = options.log ?? ((msg) => process.stdout.write(`${msg}\n`));
  const now = options.now ?? (() => new Date());

  if (!isTrustZoneId(options.trustZoneId)) {
    throw new Error(`invalid trust zone id: ${options.trustZoneId}`);
  }

  const config = buildConfig({
    repoRoot: options.repoRoot,
    home: options.home,
    binDir: options.binDir,
    trustZoneId: options.trustZoneId,
    workspaceRoot: options.workspaceRoot,
    nodePath: options.nodePath,
    updatedAt: now().toISOString(),
    ...(options.cliEntry === undefined ? {} : { cliEntry: options.cliEntry }),
    ...(options.mcpEntry === undefined ? {} : { mcpEntry: options.mcpEntry }),
    ...(options.distribution === undefined ? {} : { distribution: options.distribution }),
  });

  const steps = [];
  const ensureDir = (path, mode = 0o700) => {
    if (options.dryRun) {
      steps.push({ action: "mkdir", path, mode });
      return;
    }
    mkdir(path, { recursive: true, mode });
    chmod(path, mode);
    steps.push({ action: "mkdir", path, mode, ok: true });
  };

  const write = (path, content, mode = 0o600) => {
    if (options.dryRun) {
      steps.push({ action: "write", path, bytes: content.length, mode });
      return;
    }
    writeFile(path, content, { encoding: "utf8", mode });
    chmod(path, mode);
    steps.push({ action: "write", path, bytes: content.length, mode, ok: true });
  };

  log(`CarpeOS install-local: home=${config.home}`);
  log(`  install_root=${config.install_root}`);
  log(`  bin_dir=${config.bin_dir}`);
  log(`  trust_zone=${config.trust_zone_id}`);

  // 1) build
  if (!options.skipBuild) {
    log("Building workspace (pnpm install && pnpm build)...");
    if (!options.dryRun) {
      const install = run("pnpm", ["install"], { cwd: config.install_root });
      if (install.status !== 0) {
        throw new Error(`pnpm install failed: ${install.stderr || install.stdout}`);
      }
      const build = run("pnpm", ["build"], { cwd: config.install_root });
      if (build.status !== 0) {
        throw new Error(`pnpm build failed: ${build.stderr || build.stdout}`);
      }
    }
    steps.push({ action: "build", ok: true, dryRun: Boolean(options.dryRun) });
  }

  if (!options.dryRun && !exists(config.cli_entry)) {
    throw new Error(`CLI entry missing after build: ${config.cli_entry}`);
  }
  if (!options.dryRun && !exists(config.mcp_entry)) {
    throw new Error(`MCP entry missing after build: ${config.mcp_entry}`);
  }

  // 2) home layout
  ensureDir(config.home, 0o700);
  ensureDir(config.bin_dir, 0o755);

  write(join(config.home, CONFIG_NAME), `${JSON.stringify(config, null, 2)}\n`, 0o600);
  write(join(config.home, MCP_ENV_NAME), renderMcpEnv(config), 0o600);

  const carpeosBin = join(config.bin_dir, "carpeos");
  const mcpBin = join(config.bin_dir, "carpeos-mcp-server");
  write(carpeosBin, renderWrapper(config, "cli"), 0o755);
  write(mcpBin, renderWrapper(config, "mcp"), 0o755);

  // 3) init store
  log("Initializing local store...");
  if (!options.dryRun) {
    const init = run(
      config.node_path,
      [config.cli_entry, "init", "--home", config.home, "--trust-zone", config.trust_zone_id],
      { env: { ...process.env, CARPEOS_HOME: config.home } },
    );
    if (init.status !== 0) {
      throw new Error(`carpeos init failed: ${init.stderr || init.stdout}`);
    }
    steps.push({ action: "init", ok: true, stdout: init.stdout.trim() });
  } else {
    steps.push({ action: "init", dryRun: true });
  }

  // 4) MCP host registration
  const hostResults = [];
  if (!options.skipMcp) {
    const hosts = options.hosts ?? detectHosts(run).map((host) => host.name);
    for (const host of hosts) {
      const result = registerHostMcp({
        host,
        config,
        run,
        dryRun: Boolean(options.dryRun),
        log,
      });
      hostResults.push(result);
      steps.push({ action: "mcp_register", ...result });
    }
  }

  const state = {
    schema_version: "v1",
    record_type: "carpeos_install_state",
    installed_at: config.updated_at,
    config,
    hosts: hostResults,
    path_hint: `export PATH=${shellQuote(config.bin_dir)}:$PATH`,
  };
  write(join(config.home, STATE_NAME), `${JSON.stringify(state, null, 2)}\n`, 0o600);

  // 5) doctor-lite
  const doctor = doctorInstall({
    config,
    run,
    exists,
    skipHostProbe: options.dryRun === true,
  });
  steps.push({ action: "doctor", ...doctor });

  log("");
  log("Install complete.");
  log(`  wrappers: ${carpeosBin}`);
  log(`           ${mcpBin}`);
  log(`  config:   ${join(config.home, CONFIG_NAME)}`);
  log(`  Ensure PATH includes: ${config.bin_dir}`);
  if (doctor.ok) {
    log("  doctor: PASS");
  } else {
    log(`  doctor: FAIL — ${doctor.failures.join("; ")}`);
  }

  return { config, state, steps, doctor, hostResults };
}

/**
 * @param {typeof defaultRun} run
 */
export function detectHosts(run = defaultRun) {
  /** @type {{ name: string, command: string }[]} */
  const hosts = [];
  if (commandExists("claude", run)) {
    hosts.push({ name: "claude", command: "claude" });
  }
  if (commandExists("codex", run)) {
    hosts.push({ name: "codex", command: "codex" });
  }
  if (commandExists("grok", run)) {
    hosts.push({ name: "grok", command: "grok" });
  }
  return hosts;
}

/**
 * @param {{
 *   host: string,
 *   config: ReturnType<typeof buildConfig>,
 *   run: typeof defaultRun,
 *   dryRun: boolean,
 *   log: (msg: string) => void,
 * }} input
 */
export function registerHostMcp(input) {
  const { host, config, run, dryRun, log } = input;
  const mcpCommand = join(config.bin_dir, "carpeos-mcp-server");
  const envPairs = [
    `CARPEOS_MCP_STORE_PATH=${config.store_path}`,
    `CARPEOS_MCP_RUNTIME_DIR=${config.home}`,
    `CARPEOS_MCP_WORKSPACE_ROOT=${config.workspace_root}`,
    `CARPEOS_MCP_TRUST_ZONE=${config.trust_zone_id}`,
    `CARPEOS_MCP_VISIBLE_TRUST_ZONES=${config.trust_zone_id}`,
  ];

  if (!commandExists(host, run) && host !== "claude" && host !== "codex" && host !== "grok") {
    return { host, status: "skipped", reason: "unknown host" };
  }
  if (!commandExists(host, run)) {
    return { host, status: "skipped", reason: `${host} not on PATH` };
  }

  log(`Registering MCP with ${host}...`);
  if (dryRun) {
    return { host, status: "dry_run", mcpCommand, envPairs };
  }

  try {
    if (host === "claude") {
      // Remove prior registration if present (ignore failures).
      run("claude", ["mcp", "remove", "carpeos"]);
      const envArgs = envPairs.flatMap((pair) => ["--env", pair]);
      // Prefer user scope when available; fall back without scope.
      let result = run("claude", [
        "mcp",
        "add",
        "--scope",
        "user",
        ...envArgs,
        "--transport",
        "stdio",
        "carpeos",
        "--",
        mcpCommand,
      ]);
      if (result.status !== 0) {
        result = run("claude", [
          "mcp",
          "add",
          ...envArgs,
          "--transport",
          "stdio",
          "carpeos",
          "--",
          mcpCommand,
        ]);
      }
      return {
        host,
        status: result.status === 0 ? "registered" : "failed",
        code: result.status,
        stderr: (result.stderr || result.stdout).trim().slice(0, 500),
      };
    }

    if (host === "codex") {
      run("codex", ["mcp", "remove", "carpeos"]);
      const result = run("codex", [
        "mcp",
        "add",
        "carpeos",
        ...envPairs.flatMap((pair) => ["--env", pair]),
        "--",
        mcpCommand,
      ]);
      return {
        host,
        status: result.status === 0 ? "registered" : "failed",
        code: result.status,
        stderr: (result.stderr || result.stdout).trim().slice(0, 500),
      };
    }

    if (host === "grok") {
      // grok mcp add may not accept env flags; wrapper already sources mcp.env.
      run("grok", ["mcp", "remove", "carpeos"]);
      const result = run("grok", ["mcp", "add", "carpeos", "--", mcpCommand]);
      return {
        host,
        status: result.status === 0 ? "registered" : "failed",
        code: result.status,
        stderr: (result.stderr || result.stdout).trim().slice(0, 500),
        note: "wrapper supplies MCP env via mcp.env",
      };
    }

    return { host, status: "skipped", reason: "unsupported host" };
  } catch (error) {
    return {
      host,
      status: "failed",
      stderr: error instanceof Error ? error.message : String(error),
    };
  }
}

/**
 * @param {{
 *   config: ReturnType<typeof buildConfig>,
 *   run?: typeof defaultRun,
 *   exists?: typeof existsSync,
 *   skipHostProbe?: boolean,
 * }} input
 */
export function doctorInstall(input) {
  const run = input.run ?? defaultRun;
  const exists = input.exists ?? existsSync;
  /** @type {string[]} */
  const failures = [];
  /** @type {string[]} */
  const checks = [];

  const requirePath = (label, path) => {
    const ok = exists(path);
    checks.push(`${label}: ${ok ? "ok" : "missing"} (${path})`);
    if (!ok) {
      failures.push(`${label} missing: ${path}`);
    }
  };

  requirePath("cli_entry", input.config.cli_entry);
  requirePath("mcp_entry", input.config.mcp_entry);
  requirePath("home", input.config.home);
  requirePath("store_or_home", input.config.home);
  requirePath("wrapper_cli", join(input.config.bin_dir, "carpeos"));
  requirePath("wrapper_mcp", join(input.config.bin_dir, "carpeos-mcp-server"));
  requirePath("mcp_env", join(input.config.home, MCP_ENV_NAME));
  requirePath("config", join(input.config.home, CONFIG_NAME));

  // CLI smoke via wrapper path if present, else node entry
  const cliBin = join(input.config.bin_dir, "carpeos");
  if (exists(cliBin) || exists(input.config.cli_entry)) {
    const cmd = exists(cliBin) ? cliBin : input.config.node_path;
    const args = exists(cliBin)
      ? ["init", "--home", input.config.home, "--trust-zone", input.config.trust_zone_id]
      : [
          input.config.cli_entry,
          "init",
          "--home",
          input.config.home,
          "--trust-zone",
          input.config.trust_zone_id,
        ];
    const result = run(cmd, args, {
      env: { ...process.env, CARPEOS_HOME: input.config.home },
    });
    const ok = result.status === 0;
    checks.push(`init_smoke: ${ok ? "ok" : "fail"}`);
    if (!ok) {
      failures.push(`init smoke failed: ${(result.stderr || result.stdout).trim().slice(0, 200)}`);
    }
  }

  if (!input.skipHostProbe) {
    for (const host of ["claude", "codex", "grok"]) {
      if (!commandExists(host, run)) {
        checks.push(`${host}: not installed`);
        continue;
      }
      const list = run(host, ["mcp", "list"]);
      const text = `${list.stdout}\n${list.stderr}`;
      const hasCarpeos = /\bcarpeos\b/i.test(text);
      checks.push(`${host}_mcp: ${hasCarpeos ? "carpeos listed" : "carpeos not listed"}`);
      // Host list failure is warning-level only for doctor ok if wrappers exist
      if (!hasCarpeos) {
        failures.push(`${host}: carpeos MCP not listed (re-run install or register manually)`);
      }
    }
  }

  return {
    ok: failures.length === 0,
    failures,
    checks,
  };
}

/**
 * Shared setup / install-local CLI surface.
 *
 *   carpeos setup [<command>] [options]
 *   node scripts/install-local.mjs [<command>] [options]
 *
 * Commands:
 *   run (default)  Apply machine setup (requires --apply)
 *   plan           Print resolved plan only
 *   doctor         Verify existing install
 *   show           Show installed config
 *   help           Show help
 */

export const SETUP_COMMANDS = ["run", "plan", "doctor", "show", "help"];

/**
 * @param {string[]} argv
 */
export function parseSetupArgs(argv) {
  /** @type {{
   *  command: string,
   *  home: string,
   *  binDir: string,
   *  workspaceRoot: string,
   *  trustZone: string,
   *  registerMcp: string,
   *  repoRoot: string,
   *  skipBuild: boolean,
   *  apply: boolean,
   *  dryRun: boolean,
   *  json: boolean,
   *  help: boolean,
   *  deprecatedYes: boolean,
   * }} */
  const out = {
    command: "run",
    home: "",
    binDir: "",
    workspaceRoot: "",
    trustZone: "",
    registerMcp: "auto",
    repoRoot: "",
    skipBuild: false,
    apply: false,
    dryRun: false,
    json: false,
    help: false,
    deprecatedYes: false,
  };

  const args = [...argv];
  if (args.length === 0) {
    out.help = true;
    return out;
  }

  // Positional command
  if (args[0] && !args[0].startsWith("-")) {
    const cmd = args[0];
    if (!SETUP_COMMANDS.includes(cmd)) {
      throw new Error(`unknown setup command: ${cmd}\nRun with --help for usage.`);
    }
    out.command = cmd;
    args.shift();
  }

  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    const need = (name) => {
      const value = args[++i];
      if (value === undefined || value.startsWith("-")) {
        throw new Error(`missing value for ${name}`);
      }
      return value;
    };

    if (arg === "--help" || arg === "-h") {
      out.help = true;
    } else if (arg === "--apply") {
      out.apply = true;
    } else if (arg === "--yes" || arg === "-y") {
      // Backward-compatible alias; prefer --apply in docs and help.
      out.apply = true;
      out.deprecatedYes = true;
    } else if (arg === "--dry-run") {
      out.dryRun = true;
      // dry-run is plan-only; do not require --apply
      if (out.command === "run") {
        out.command = "plan";
      }
    } else if (arg === "--json") {
      out.json = true;
    } else if (arg === "--skip-build") {
      out.skipBuild = true;
    } else if (arg === "--skip-mcp") {
      out.registerMcp = "none";
    } else if (arg === "--home") {
      out.home = need("--home");
    } else if (arg === "--bin-dir") {
      out.binDir = need("--bin-dir");
    } else if (arg === "--workspace-root") {
      out.workspaceRoot = need("--workspace-root");
    } else if (arg === "--trust-zone") {
      out.trustZone = need("--trust-zone");
    } else if (arg === "--register-mcp") {
      out.registerMcp = need("--register-mcp");
    } else if (arg === "--hosts") {
      // Alias for --register-mcp (older docs)
      out.registerMcp = need("--hosts");
    } else if (arg === "--repo-root") {
      out.repoRoot = need("--repo-root");
    } else if (arg === "--doctor") {
      out.command = "doctor";
    } else if (arg === "--plan") {
      out.command = "plan";
    } else {
      throw new Error(`unknown option: ${arg}\nRun with --help for usage.`);
    }
  }

  if (out.command === "help") {
    out.help = true;
  }
  return out;
}

/** @deprecated use parseSetupArgs */
export function parseInstallArgs(argv) {
  return parseSetupArgs(argv);
}

/**
 * @param {{ programName?: string, includeRepoRoot?: boolean }} [opts]
 */
export function formatSetupHelp(opts = {}) {
  const program = opts.programName ?? "carpeos setup";
  const repoLine = opts.includeRepoRoot
    ? "  --repo-root <path>          Git checkout root (default: auto-detect)\n  --skip-build                Skip pnpm install/build (checkout installer)\n"
    : "";
  return `${program} — configure local CarpeOS runtime and agent MCP hosts

USAGE
  ${program} <command> [options]
  ${program} [options]                 # same as: run

COMMANDS
  run       Apply setup to this machine (requires --apply)
  plan      Show resolved paths and actions without changing anything
  doctor    Verify an existing install
  show      Print installed config.json (if present)
  help      Show this help

OPTIONS
  --home <path>               Private runtime home
                              (default: $CARPEOS_HOME or ~/.carpeos)
  --bin-dir <path>            Where to install carpeos wrappers
                              (default: $CARPEOS_BIN_DIR or ~/.local/bin)
  --workspace-root <path>     Default workspace root exposed to MCP
                              (default: $HOME)
  --trust-zone <id|auto>      Trust zone id (default: tz_local_default)
                              Use "auto" for a stable host-derived id
  --register-mcp <spec>       Who gets MCP registration:
                              auto | none | claude,codex,grok
                              (default: auto = every host CLI found on PATH)
${repoLine}  --apply                     Apply changes (required for "run")
  --dry-run                   Alias for "plan" (no changes)
  --json                      Machine-readable JSON on stdout
  -h, --help                  Show help

SAFETY
  Setup never mutates the machine unless you pass --apply.
  Without --apply, it prints the plan (or help) and exits.

EXAMPLES
  # See what would happen with defaults
  ${program} plan

  # Apply default setup (home, wrappers, MCP for detected hosts)
  ${program} run --apply

  # Custom home + only Claude MCP
  ${program} run --apply \\
    --home "$HOME/.carpeos" \\
    --trust-zone tz_local_default \\
    --register-mcp claude

  # Check health after install
  ${program} doctor

  # Inspect saved config
  ${program} show

NOTES
  --yes / -y still work as an alias for --apply (deprecated).
  Session capture hooks (adapters/) are separate from MCP registration.
`;
}

/**
 * Resolve concrete plan values from parsed args + environment.
 * @param {ReturnType<typeof parseSetupArgs>} args
 * @param {{
 *   env?: NodeJS.ProcessEnv,
 *   nodePath?: string,
 *   defaultRepoRoot?: string,
 *   distribution?: string,
 *   cliEntry?: string,
 *   mcpEntry?: string,
 * }} [ctx]
 */
export function resolveSetupPlan(args, ctx = {}) {
  const env = ctx.env ?? process.env;
  const home = args.home ? resolve(args.home) : defaultHome(env);
  const binDir = args.binDir ? resolve(args.binDir) : defaultBinDir(env);
  const workspaceRoot = args.workspaceRoot ? resolve(args.workspaceRoot) : env.HOME || homedir();
  let trustZone = args.trustZone || DEFAULT_TRUST_ZONE;
  if (trustZone === "auto") {
    trustZone = trustZoneFromHostname();
  }
  if (!isTrustZoneId(trustZone)) {
    throw new Error(
      `invalid --trust-zone "${args.trustZone || trustZone}" (expected tz_[a-z0-9]… or auto)`,
    );
  }

  const registerMcp = String(args.registerMcp || "auto").trim();
  let hostList;
  let skipMcp = false;
  if (registerMcp === "none" || registerMcp === "off" || registerMcp === "false") {
    skipMcp = true;
    hostList = [];
  } else if (registerMcp === "auto") {
    skipMcp = false;
    hostList = undefined; // detect at apply time
  } else {
    skipMcp = false;
    hostList = registerMcp
      .split(",")
      .map((h) => h.trim())
      .filter(Boolean);
    for (const h of hostList) {
      if (!["claude", "codex", "grok"].includes(h)) {
        throw new Error(
          `invalid --register-mcp host "${h}" (allowed: auto, none, claude, codex, grok)`,
        );
      }
    }
  }

  const repoRoot = args.repoRoot
    ? resolve(args.repoRoot)
    : (ctx.defaultRepoRoot ?? defaultRepoRoot());

  return {
    command: args.command,
    apply: Boolean(args.apply) && args.command === "run" && !args.dryRun,
    dryRun: Boolean(args.dryRun) || args.command === "plan",
    json: Boolean(args.json),
    skipBuild: Boolean(args.skipBuild),
    skipMcp,
    home,
    binDir,
    workspaceRoot,
    trustZoneId: trustZone,
    registerMcp,
    hostList,
    repoRoot,
    nodePath: ctx.nodePath ?? process.execPath,
    distribution: ctx.distribution,
    cliEntry: ctx.cliEntry,
    mcpEntry: ctx.mcpEntry,
    deprecatedYes: Boolean(args.deprecatedYes),
    actions: [
      "Ensure runtime home directory exists",
      "Write config.json and mcp.env (mode 0600)",
      "Install carpeos + carpeos-mcp-server wrappers into bin-dir",
      skipMcp
        ? "Skip agent MCP registration (--register-mcp none)"
        : registerMcp === "auto"
          ? "Register MCP with every host CLI found on PATH (claude/codex/grok)"
          : `Register MCP with: ${hostList?.join(", ")}`,
      "Initialize local store (carpeos init)",
      "Run doctor checks",
    ],
  };
}

/**
 * @param {ReturnType<typeof resolveSetupPlan>} plan
 */
export function formatSetupPlanHuman(plan) {
  const lines = [
    "CarpeOS setup plan",
    "──────────────────",
    `  command:          ${plan.command}`,
    `  apply changes:    ${plan.apply ? "yes (--apply)" : "no (plan only)"}`,
    `  home:             ${plan.home}`,
    `  bin-dir:          ${plan.binDir}`,
    `  workspace-root:   ${plan.workspaceRoot}`,
    `  trust-zone:       ${plan.trustZoneId}`,
    `  register-mcp:     ${plan.registerMcp}`,
    `  distribution:     ${plan.distribution ?? "git-or-auto"}`,
    `  skip-build:       ${plan.skipBuild}`,
    "",
    "Actions:",
    ...plan.actions.map((a) => `  • ${a}`),
    "",
  ];
  if (!plan.apply && plan.command === "run") {
    lines.push(
      "Nothing will be changed yet.",
      "Re-run with the same options plus --apply to execute.",
      "",
    );
  }
  if (plan.deprecatedYes) {
    lines.push("Note: --yes is deprecated; use --apply instead.", "");
  }
  return lines.join("\n");
}
